version: '3.8'
services:
  # 1. 数据库服务（最先启动）
  mysql:
    container_name: hr-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: 3306
      MYSQL_SERVER: localhost
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 5
      interval: 30s
      start_period: 60s
    command: --default-authentication-plugin=mysql_native_password

  # 2. 后端服务（依赖数据库）
  hr-backend:
    container_name: hr-backend
    image: 127.0.0.1:8080/hr-assist/hr-backend:${BACKTEND_TAG}
    restart: always
    depends_on:
      - mysql
    environment:
      - MYSQL_SERVER=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DB=${MYSQL_DATABASE}
      - MYSQL_PORT=3306
    ports:
      - "8000:8000"
    networks:
      - backend

  # hr-pay:
  #   container_name: hr-pay
  #   image: 127.0.0.1:8080/hr-assist/hr-pay:latest
  #   restart: always
  #   depends_on:
  #     - mysql
  #   ports:
  #     - "9000:9000"
  #   networks:
  #     - backend

  # 3. 前端服务
  frontend:
    container_name: hr-frontend
    image: 127.0.0.1:8080/hr-assist/hr-assistant-front:${FRONTEND_TAG}
    restart: always
    ports:
      - "3000:3000"
    networks:
      - backend

  # 4. 网关服务
  nginx:
    container_name: hr-nginx
    image: nginx:latest
    depends_on:
      - frontend
      - hr-backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge 