version: '3.8'
services:
  # 1. 数据库服务（最先启动）
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - backend

  # 2. 后端服务（依赖数据库）
  hr-backend:
    image: your-harbor.com/your-project/hr-backend:${BACKTEND_TAG}
    restart: always
    depends_on:
      - mysql
      - redis
    environment:
      - DATABASE_URL=mysql://root:your_password@mysql:3306/hr_db
      - REDIS_URL=redis://redis:6379
    networks:
      - backend

  hr-pay:
    image: your-harbor.com/your-project/hr-pay:latest
    restart: always
    depends_on:
      - mysql
    networks:
      - backend

  # 3. 前端服务
  frontend:
    image: 127.0.0.1:8080/hr-assist/hr-assistant-front:${FRONTEND_TAG}
    restart: always
    ports:
      - "3000:3000"
    networks:
      - backend

  # 4. 网关服务
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - hr-backend
      - hr-pay
      - frontend
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge 