name: Deploy Database Services

on:
  workflow_dispatch:

jobs:
  deploy-db:
    runs-on: ubuntu-latest
    environment: production # 指定环境名称

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          key: ${{ secrets.ALIYUN_SSH_KEY }}
          port: 22
          script: |
          
            # 预先拉取镜像，带重试机制
            echo "Pulling MySQL image..."
            docker pull mysql:8.0 || docker pull registry.cn-hangzhou.aliyuncs.com/library/mysql:8.0
            
            echo "Pulling Redis image..."
            docker pull registry.cn-hangzhou.aliyuncs.com/library/redis:7-alpine || docker pull redis:7-alpine
            
            # 只启动数据库服务（使用官方镜像，无需登录 Harbor）
            docker-compose up -d mysql redis