name: Deploy Database Services

on:
  workflow_dispatch:

jobs:
  deploy-db:
    runs-on: ubuntu-latest
    environment: production # 指定环境名称

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          key: ${{ secrets.ALIYUN_SSH_KEY }}
          port: 22
          script: |
            # 进入项目目录
            cd /opt/hr-deploy
            
            # 检查 docker-compose.yml 文件是否存在
            if [ ! -f docker-compose.yml ]; then
              echo "Error: docker-compose.yml not found in /opt/hr-deploy"
              exit 1
            fi
            
            # 检查是否有 MySQL 容器在运行
            if docker ps | grep -q mysql; then
              echo "MySQL container is running, stopping it first..."
              docker-compose stop mysql || true
              docker-compose rm -f mysql || true
            fi
            
            # 启动数据库服务（Docker Compose 会自动拉取镜像），自动确认
            echo "y" | docker-compose up -d mysql