name: Deploy Database Services

on:
  workflow_dispatch:

jobs:
  deploy-db:
    runs-on: ubuntu-latest
    environment: production # 指定环境名称

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          key: ${{ secrets.ALIYUN_SSH_KEY }}
          port: 22
          script: |
            # 进入项目目录
            cd /opt/hr-deploy
            
            # 检查 docker-compose.yml 文件是否存在
            if [ ! -f docker-compose.yml ]; then
              echo "Error: docker-compose.yml not found in /opt/hr-deploy"
              exit 1
            fi
            
            # 检查是否有 MySQL 容器在运行（兼容新旧容器名称）
            if docker ps | grep -q "mysql.*hr-deploy\|hr-mysql"; then
              echo "MySQL 容器正在运行，停止并删除..."
              docker-compose down || true
              docker rm -f hr-mysql || true
              docker rm -f hr-deploy_mysql_1 || true
            elif docker ps -a | grep -q "mysql.*hr-deploy\|hr-mysql"; then
              echo "MySQL 容器存在但未运行，删除容器..."
              docker rm -f hr-mysql || true
              docker rm -f hr-deploy_mysql_1 || true
            else
              echo "MySQL 容器不存在，直接启动..."
            fi
            
            # 启动数据库服务
            echo "启动 MySQL 服务..."
            docker-compose up -d mysql
            
            # 等待服务启动（增加等待时间）
            echo "等待 MySQL 服务启动..."
            sleep 60
            
            # 检查服务状态
            echo "检查 MySQL 服务状态..."
            docker-compose ps mysql
            
            # 等待 MySQL 完全启动
            echo "等待 MySQL 完全启动..."
            for i in {1..30}; do
              if docker-compose exec -T mysql mysqladmin ping -h localhost --silent 2>/dev/null; then
                echo "✅ MySQL 服务启动成功！"
                exit 0
              fi
              echo "等待 MySQL 启动... ($i/30)"
              sleep 10
            done
            
            echo "❌ MySQL 服务启动失败，查看日志..."
            docker-compose logs mysql
            exit 1