name: Start Nginx Service

on:
  workflow_dispatch:

jobs:
  start-nginx:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Start Nginx
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          key: ${{ secrets.ALIYUN_SSH_KEY }}
          port: 22
          script: |
            cd /opt/hr-deploy
            
            echo "检查当前服务状态..."
            docker-compose ps
            
            echo "检查是否有旧的 nginx 服务在运行..."
            if docker ps | grep -q hr-nginx; then
              echo "发现旧的 nginx 服务，正在停止..."
              docker-compose stop nginx || true
              docker rm -f hr-nginx || true
              echo "旧的 nginx 服务已停止"
            else
              echo "没有发现旧的 nginx 服务"
            fi
            
            echo "启动 nginx 服务..."
            docker-compose up -d nginx
            
            echo "等待 nginx 启动..."
            sleep 10
            
            echo "检查 nginx 状态..."
            docker-compose ps nginx
            
            echo "检查 nginx 日志..."
            docker-compose logs nginx || echo "无法查看 nginx 日志"
            
            echo "检查所有服务状态..."
            docker-compose ps
            
            echo "测试 nginx 是否响应..."
            if curl -I http://localhost:80/ > /dev/null 2>&1; then
              echo "✅ nginx 启动成功并正常响应！"
            else
              echo "❌ nginx 启动失败或无响应"
              echo "检查 nginx 容器状态..."
              docker ps | grep nginx || echo "nginx 容器未运行"
              echo "检查 nginx 详细日志..."
              docker-compose logs nginx --tail=20
              exit 1
            fi 